// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xovwekuqdmbrbtctxhgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvdndla3VxZG1icmJ0Y3R4aGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDk3NjgsImV4cCI6MjA2NzgyNTc2OH0.PPirP9y2Dp2UIfCsKbD4_QXnk8W8R9vs599lMYC4V-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});